name: run tests

on:
  push:
    branches:
    - "*"
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5] #, 3.6, 3.7, 3.8, 3.9]
        
    steps:
      - uses: actions/checkout@v2
